# Ubuntu 16.04 ships with Python 3 by default, which is unsupported by Ansible
- hosts: servers
  gather_facts: False
  tasks:
    - name: Install Python 2
      raw: apt-get update -qq && apt-get install -qq python-minimal

- hosts: servers
  roles:
    - libbitcoin_server
